// Filename: base-schema.ts
// Path: @/app/(dashboard)/foundation/configuration/gl-mapping
// import { z } from "zod";

// export const baseSchema = z.object({
//   code: z.coerce.number().int().nonnegative(),
//   pnl_head: z.string().min(1, "Name is required"),
//   type: z.enum(["income", "expense"]),
//   group: z.string(),
//   description: z.string(),
// });
// import { z } from "zod";

// export const baseSchema = z.object({
//   id: z.number().int().nonnegative(), // auto-generated
//   created_at: z.string().datetime().optional(),  // optional, generated by DB
//   name: z.string().min(1, "Name is required"),
//   user_id: z.coerce.number().int().nonnegative(),
//   dept_id: z.number().int().nonnegative(),
// });

//export type Schema = z.infer<typeof schema>;
import { z } from "zod";

export const baseSchema = z.object({
  id: z.number().int().nonnegative(), // bigint
//  created_at: z.string().datetime(),  // timestamp with time zone (ISO string)
  name: z.string().min(1),            // varchar not null
  user_id: z.coerce.number().int().nonnegative(), // bigint primary key
  department: z.string().min(1, "Department is required"), // bigint not null
  entity_id: z.number().int().nonnegative().nullable(), // bigint nullable
  email: z.string().email().nullable(), // email field (nullable text)
});
//export type Schema = z.infer<typeof schema>;